### ISSUE TITLE
bin files in source control

### ISSUE THREAD

**Issue by simonjduff** [jaduff/course_site#2]
You added a bunch of bin/obj files in source control by accident. You'll want to remove these from the git history. This [documentation](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) should help

**Comment by jaduff** [comment]
Hmmm, bin/ is in the .gitignore file. Maybe it needs to be bin/* to filter properly?

**Comment by simonjduff** [comment]
Once you've committed a file, if you subsequently ignore it, it stays
